# Generated by Django 3.1.4 on 2021-01-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Öğrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20, verbose_name='İsim')),
                ('no', models.CharField(max_length=8, verbose_name='Okul Numara')),
                ('ders', models.TextField(max_length=160, verbose_name='Aldığı Dersler')),
                ('saat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
